<?php

/**
* Implements hook_cron().
*/

function user_create_cron() {
	$current_time = \Drupal::time()->getRequestTime();
	$past_time = $current_time - 86440;

	$database = \Drupal::database();
	$fetch_query = $database->query("SELECT `uid`, `status`, `created` FROM `users_field_data` WHERE `status` = 0 && `created` < ".$current_time." && `created` > ".$past_time.";");
	$query_result = $fetch_query->fetchAll();

	foreach($query_result as $result){
		$update_time = \Drupal::time()->getRequestTime();
		$update_query = $database->update('users_field_data')
		->fields(array('status' => 1, 'changed' => $update_time))
		->condition('uid', $result->uid)
		->execute();
	}
	\Drupal::logger('user_create')->notice('Cron run for user approval complete');
}
