<?php
/**
* @file
* Contains userdata.module.
*/
use Drupal\Core\Routing\RouteMatchInterface;

/**
* Implements hook_help().
*/
function userdata_help($route_name, RouteMatchInterface $route_match) {
	switch ($route_name) {
		// Main module help for the userdata module.
		case 'help.page.userdata':
			$output = '';
			$output .= '<h3>'.t('About').'</h3>';
			$output .= '<p>'.t('This dispaly information what you enter your application.').'</p>';
			return $output;
		default:
	}
}

function userdata_theme() {
	// We use a template file to allow for translation of blocks of content.
	// Therefore we need to add this content at the theming layer.
	return [
		'userdata_description' => [
			'template' => 'description',
			'variables' => [],
		],
	];
}